# The containers that compose the project
services:
  moneytrack_local_dev_db:
    image: postgres:16
    restart: always
    container_name: moneytrack_local_dev_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local_dev_db
