import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { Theme } from '@radix-ui/themes'

import './globals.css'
import AuthProvider from '@/components/AuthProvider/AuthProvider'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
          <main>
            <Theme
              scaling="110%"
              appearance="dark"
              panelBackground="translucent"
              accentColor="iris"
              grayColor="slate"
              radius="full"
            >
              {/* <ThemePanel /> */}
              {children}
            </Theme>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
